---
abstract: 'Spartans! What is I<your> API?'
author:
  - 'Arun Prasaad <arunbear@cpan.org>'
build_requires:
  Test::Lib: '0.002'
  Test::Most: '0.34'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, Dist::Milla version v1.0.8, CPAN::Meta::Converter version 2.142690'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Class-Minion
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Exception::Class: '1.38'
  List::MoreUtils: '0.33'
  Package::Stash: '0.36'
  Params::Validate: '1.10'
  Sub::Name: '0.09'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/arunbear/Class-Minion/issues
  homepage: https://github.com/arunbear/Class-Minion
  repository: https://github.com/arunbear/Class-Minion.git
version: '0.000002'
x_contributors:
  - 'Arun Prasaad <arunbear@gmail.com>'
  - 'arunbear <arunbear@gmail.com>'
